### ISSUE TITLE
Serializer doesn't reorder objects in parentheses

### ISSUE THREAD

**Issue by wslooney** [edmcouncil/rdf-toolkit#20]
In a turtle file, the elements in parentheses, for example, owl:intersectionOf (...) are not re-ordered by the serializer. Protege does alphabetically re-order these constructions. So if one team member edits on Protege and another edits the code directly, they may not match after being run through the serializer.

**Comment by wslooney** [comment]
So, I was wrong about Protege. It does reorder classes inside of the constructions like owl:intersectionOf(...), but not always alphabetically.

**Comment by wslooney** [comment]
Any update on this?

**Comment by mereolog** [comment]
> Any update on this?

Unfortunately, this is still on waiting list.

**Comment by ajnelson-nist** [comment]
Hello,

Is this referring to Turtle syntactic sugar of `( ... )` corresponding to `rdf:List`?  If so, I do not believe this issue is appropriate for consideration.  `rdf:List` is order-dependent, so sorting would destroy the original list and create a new one.  See e.g. Examples 20 vs. 21 in [Turtle, Section 3](https://www.w3.org/TR/turtle/#sec-examples).  This would alter behavior of some RDF graphs, such as SHACL complex `sh:path` expressions; see e.g. [SHACL, Section 2.3](https://www.w3.org/TR/shacl/#property-shapes), first example containing `sh:path (ex:knows ex:email) ;`.

**Comment by mereolog** [comment]
> Hello,
> 
> Is this referring to Turtle syntactic sugar of `( ... )` corresponding to `rdf:List`? If so, I do not believe this issue is appropriate for consideration. `rdf:List` is order-dependent, so sorting would destroy the original list and create a new one. See e.g. Examples 20 vs. 21 in [Turtle, Section 3](https://www.w3.org/TR/turtle/#sec-examples). This would alter behavior of some RDF graphs, such as SHACL complex `sh:path` expressions; see e.g. [SHACL, Section 2.3](https://www.w3.org/TR/shacl/#property-shapes), first example containing `sh:path (ex:knows ex:email) ;`.

Yes, that's a valid general point.
However, in such cases when lists are used by owl:intersectionOf constructs we could reshuffle them with no semantic impact.
