### ISSUE TITLE
Comments disappear after serialization

### ISSUE THREAD

**Issue by uscholdm** [edmcouncil/rdf-toolkit#23]
Comments disappear after serialization. Comments on separate lines disappear as well as comments at the end of a line. This is my experience with Turtle files. I have not tested the behavior for other syntaxes.

It would be very nice if there was a way to keep them.

**Comment by mereolog** [comment]
We are looking into this issue and will get back to you shortly.

**Comment by uscholdm** [comment]
Yes, I see it is not very clear how to handle different kinds of comments. There may be no way to preserve the big header ones that highlight major section such as:
```
#################################################################
#    Annotation properties
#################################################################
```

So, I guess this is not so easy to do.  I wonder if anyone else has expressed an interest in this.

**Comment by mereolog** [comment]
> So, I guess this is not so easy to do. I wonder if anyone else has expressed an interest in this.

No, not yet.

**Comment by ElisaKendall** [comment]
We have actually asked for removal of comments for FIBO and our pharma and IOF projects because Protege, via the OWL API, adds so much useless white space, making it difficult to review an ontology in GitHub as well as simply by visual comparison. If we were to add such a feature, it would be nice if there is some additional character embedded in the comment, such as an asterisk after the "<-- ", something like "<--* ", as a trigger for preserving the comment.

**Comment by rjyounes** [comment]
I share the preference for annotations, such as `skos:scopeNote`, and `skos:editorialNote`, rather than comments.
