### ISSUE TITLE
udl option adds language tags to typed literals

### ISSUE THREAD

**Issue by rjyounes** [edmcouncil/rdf-toolkit#79]
The `udl` option should add language tags only to literals that are untyped and untagged. I am finding that it changes `^^xsd:string` to language tags in Turtle files. I believe RDF/XML and JSON-LD work as expected.

**Comment by mereolog** [comment]
@rjyounes thanks for your feedback.

Would you mind checking whether https://jenkins.edmcouncil.org/view/rdf-toolkit/job/rdf-toolkit-build-dev/30/artifact/target/rdf-toolkit.jar fixes the issue?

**Comment by rjyounes** [comment]
No, the problem is unfortunately not fixed. Given the following input:

```
told:_Website_84000
	skos:prefLabel "84000"^^xsd:string ;
        tolo:displayLabel "84000" ;
	tolo:url "https://84000.co/"^^xsd:anyURI ;
	.
```

Running the serializer as:

```
java -jar rdf-toolkit.jar -udl en -tfmt turtle -sdt explicit -dtd -ibn -sni -s file.ttl -t newfile.ttl
```

The output is:

```
told:_Website_84000
	skos:prefLabel "84000"@en ;
        tolo:displayLabel "84000"@en ;
	tolo:url "https://84000.co/"^^xsd:anyURI ;
	.
```

The expected output is 

```
told:_Website_84000
	skos:prefLabel "84000"^^xsd:string ;
        tolo:displayLabel "84000"@en ;
	tolo:url "https://84000.co/"^^xsd:anyURI ;
	.
```

**Comment by mereolog** [comment]
@rjyounes I have had a look into the RDF specification and for instance https://www.w3.org/TR/rdf-concepts/#section-Graph-Literal says that the default datatype for an untyped literal is XMLSchema:string. A similar information can be found in https://www.w3.org/TR/rdf11-primer/#section-n-triples.

So in a sense the udl option does not make sense because there are no untyped literals in RDF graphs - if we think about implicit datatypes.

We can probably search for explicitly untyped literals but the tool we are using, i.e., rdf4j, does not support this, so an extension liks this would require quite an effort.

**Comment by rjyounes** [comment]
I see, that makes sense. I think it still makes sense to include the option, as long as the above behavior is properly understood by users. You could, for instance, change the description to "add default language tag to explicitly or implicitly typed string literals."
